//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Game/Input/GameControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControl"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""375bfbc2-de80-474b-8c5e-1f1b75ca10ca"",
            ""actions"": [
                {
                    ""name"": ""Wheel Scroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f394cc79-2393-4adf-a047-7e1563e4d4b2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right Click"",
                    ""type"": ""Button"",
                    ""id"": ""b27fa577-b493-4628-b57f-bec45dc9fec2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Primary Position"",
                    ""type"": ""PassThrough"",
                    ""id"": ""59f2980a-25c7-4cf4-8f6a-57b2b11dc9ee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Primary Contact"",
                    ""type"": ""Button"",
                    ""id"": ""94253781-4904-45b5-9c9a-b22a08d16ed9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""da0e5a8f-ff08-4d9e-9280-69b4fe641d7f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""6a2afd36-68fc-4e59-b9a5-9ca46599c5cb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryTouchContact"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6a5a94df-9ff9-4c27-bc45-eba0a307ac69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Primary Long"",
                    ""type"": ""Button"",
                    ""id"": ""eb2ed5a7-4839-4a47-bf08-b77967783f93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1,pressPoint=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b5466fc1-2624-444c-9e49-41b5cc54e67d"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wheel Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e98e2fe4-5f75-472e-a1f1-1b021331bd65"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ceae1c41-4642-473c-abe3-7331eb316f96"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""730a6dc9-8004-4608-be93-265130d50989"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b21a0ef4-3a64-400a-9ea2-fe47e74e7396"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Contact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52e33742-0142-4f16-b726-11fa13c24719"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Contact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07e38350-6a8c-4ca2-963f-03e9d585e282"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""867e304b-78e3-4f71-ae83-b2874d28bb57"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edc98727-9227-48ca-81e7-b2a5d127a6c5"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7f1813e-d22a-4e8d-9ef3-b49ab993d67b"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb323602-6cbe-4a70-9d75-dce149be6ef4"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""Hold(duration=1,pressPoint=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Long"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fc1f796-e641-4804-8785-6af37c68bc7c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Long"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_WheelScroll = m_GamePlay.FindAction("Wheel Scroll", throwIfNotFound: true);
        m_GamePlay_RightClick = m_GamePlay.FindAction("Right Click", throwIfNotFound: true);
        m_GamePlay_PrimaryPosition = m_GamePlay.FindAction("Primary Position", throwIfNotFound: true);
        m_GamePlay_PrimaryContact = m_GamePlay.FindAction("Primary Contact", throwIfNotFound: true);
        m_GamePlay_PrimaryFingerPosition = m_GamePlay.FindAction("PrimaryFingerPosition", throwIfNotFound: true);
        m_GamePlay_SecondaryFingerPosition = m_GamePlay.FindAction("SecondaryFingerPosition", throwIfNotFound: true);
        m_GamePlay_SecondaryTouchContact = m_GamePlay.FindAction("SecondaryTouchContact", throwIfNotFound: true);
        m_GamePlay_PrimaryLong = m_GamePlay.FindAction("Primary Long", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private IGamePlayActions m_GamePlayActionsCallbackInterface;
    private readonly InputAction m_GamePlay_WheelScroll;
    private readonly InputAction m_GamePlay_RightClick;
    private readonly InputAction m_GamePlay_PrimaryPosition;
    private readonly InputAction m_GamePlay_PrimaryContact;
    private readonly InputAction m_GamePlay_PrimaryFingerPosition;
    private readonly InputAction m_GamePlay_SecondaryFingerPosition;
    private readonly InputAction m_GamePlay_SecondaryTouchContact;
    private readonly InputAction m_GamePlay_PrimaryLong;
    public struct GamePlayActions
    {
        private @GameControl m_Wrapper;
        public GamePlayActions(@GameControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @WheelScroll => m_Wrapper.m_GamePlay_WheelScroll;
        public InputAction @RightClick => m_Wrapper.m_GamePlay_RightClick;
        public InputAction @PrimaryPosition => m_Wrapper.m_GamePlay_PrimaryPosition;
        public InputAction @PrimaryContact => m_Wrapper.m_GamePlay_PrimaryContact;
        public InputAction @PrimaryFingerPosition => m_Wrapper.m_GamePlay_PrimaryFingerPosition;
        public InputAction @SecondaryFingerPosition => m_Wrapper.m_GamePlay_SecondaryFingerPosition;
        public InputAction @SecondaryTouchContact => m_Wrapper.m_GamePlay_SecondaryTouchContact;
        public InputAction @PrimaryLong => m_Wrapper.m_GamePlay_PrimaryLong;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void SetCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterface != null)
            {
                @WheelScroll.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnWheelScroll;
                @WheelScroll.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnWheelScroll;
                @WheelScroll.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnWheelScroll;
                @RightClick.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnRightClick;
                @PrimaryPosition.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryPosition;
                @PrimaryPosition.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryPosition;
                @PrimaryPosition.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryPosition;
                @PrimaryContact.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryContact;
                @PrimaryContact.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryContact;
                @PrimaryContact.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryContact;
                @PrimaryFingerPosition.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryFingerPosition;
                @PrimaryFingerPosition.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryFingerPosition;
                @PrimaryFingerPosition.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryFingerPosition;
                @SecondaryFingerPosition.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSecondaryFingerPosition;
                @SecondaryFingerPosition.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSecondaryFingerPosition;
                @SecondaryFingerPosition.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSecondaryFingerPosition;
                @SecondaryTouchContact.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSecondaryTouchContact;
                @SecondaryTouchContact.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSecondaryTouchContact;
                @SecondaryTouchContact.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSecondaryTouchContact;
                @PrimaryLong.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryLong;
                @PrimaryLong.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryLong;
                @PrimaryLong.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPrimaryLong;
            }
            m_Wrapper.m_GamePlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @WheelScroll.started += instance.OnWheelScroll;
                @WheelScroll.performed += instance.OnWheelScroll;
                @WheelScroll.canceled += instance.OnWheelScroll;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @PrimaryPosition.started += instance.OnPrimaryPosition;
                @PrimaryPosition.performed += instance.OnPrimaryPosition;
                @PrimaryPosition.canceled += instance.OnPrimaryPosition;
                @PrimaryContact.started += instance.OnPrimaryContact;
                @PrimaryContact.performed += instance.OnPrimaryContact;
                @PrimaryContact.canceled += instance.OnPrimaryContact;
                @PrimaryFingerPosition.started += instance.OnPrimaryFingerPosition;
                @PrimaryFingerPosition.performed += instance.OnPrimaryFingerPosition;
                @PrimaryFingerPosition.canceled += instance.OnPrimaryFingerPosition;
                @SecondaryFingerPosition.started += instance.OnSecondaryFingerPosition;
                @SecondaryFingerPosition.performed += instance.OnSecondaryFingerPosition;
                @SecondaryFingerPosition.canceled += instance.OnSecondaryFingerPosition;
                @SecondaryTouchContact.started += instance.OnSecondaryTouchContact;
                @SecondaryTouchContact.performed += instance.OnSecondaryTouchContact;
                @SecondaryTouchContact.canceled += instance.OnSecondaryTouchContact;
                @PrimaryLong.started += instance.OnPrimaryLong;
                @PrimaryLong.performed += instance.OnPrimaryLong;
                @PrimaryLong.canceled += instance.OnPrimaryLong;
            }
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);
    public interface IGamePlayActions
    {
        void OnWheelScroll(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnPrimaryPosition(InputAction.CallbackContext context);
        void OnPrimaryContact(InputAction.CallbackContext context);
        void OnPrimaryFingerPosition(InputAction.CallbackContext context);
        void OnSecondaryFingerPosition(InputAction.CallbackContext context);
        void OnSecondaryTouchContact(InputAction.CallbackContext context);
        void OnPrimaryLong(InputAction.CallbackContext context);
    }
}
